/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatesIndexRouteImport } from './routes/states.index'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as FoodsIndexRouteImport } from './routes/foods.index'
import { Route as StatesSlugRouteImport } from './routes/states.$slug'
import { Route as FoodsSlugRouteImport } from './routes/foods.$slug'
import { Route as GuidesLicenseCostStateRouteImport } from './routes/guides.license-cost.$state'
import { Route as GuidesLabelingStateRouteImport } from './routes/guides.labeling.$state'
import { Route as GuidesSellFoodStateRouteImport } from './routes/guides.sell.$food.$state'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesIndexRoute = StatesIndexRouteImport.update({
  id: '/states/',
  path: '/states/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsIndexRoute = FoodsIndexRouteImport.update({
  id: '/foods/',
  path: '/foods/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesSlugRoute = StatesSlugRouteImport.update({
  id: '/states/$slug',
  path: '/states/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsSlugRoute = FoodsSlugRouteImport.update({
  id: '/foods/$slug',
  path: '/foods/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesLicenseCostStateRoute = GuidesLicenseCostStateRouteImport.update({
  id: '/guides/license-cost/$state',
  path: '/guides/license-cost/$state',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesLabelingStateRoute = GuidesLabelingStateRouteImport.update({
  id: '/guides/labeling/$state',
  path: '/guides/labeling/$state',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSellFoodStateRoute = GuidesSellFoodStateRouteImport.update({
  id: '/guides/sell/$food/$state',
  path: '/guides/sell/$food/$state',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compare': typeof CompareRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/foods/$slug': typeof FoodsSlugRoute
  '/states/$slug': typeof StatesSlugRoute
  '/foods/': typeof FoodsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/states/': typeof StatesIndexRoute
  '/guides/labeling/$state': typeof GuidesLabelingStateRoute
  '/guides/license-cost/$state': typeof GuidesLicenseCostStateRoute
  '/guides/sell/$food/$state': typeof GuidesSellFoodStateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compare': typeof CompareRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/foods/$slug': typeof FoodsSlugRoute
  '/states/$slug': typeof StatesSlugRoute
  '/foods': typeof FoodsIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/states': typeof StatesIndexRoute
  '/guides/labeling/$state': typeof GuidesLabelingStateRoute
  '/guides/license-cost/$state': typeof GuidesLicenseCostStateRoute
  '/guides/sell/$food/$state': typeof GuidesSellFoodStateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compare': typeof CompareRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/foods/$slug': typeof FoodsSlugRoute
  '/states/$slug': typeof StatesSlugRoute
  '/foods/': typeof FoodsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/states/': typeof StatesIndexRoute
  '/guides/labeling/$state': typeof GuidesLabelingStateRoute
  '/guides/license-cost/$state': typeof GuidesLicenseCostStateRoute
  '/guides/sell/$food/$state': typeof GuidesSellFoodStateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/compare'
    | '/sitemap.xml'
    | '/foods/$slug'
    | '/states/$slug'
    | '/foods/'
    | '/guides/'
    | '/states/'
    | '/guides/labeling/$state'
    | '/guides/license-cost/$state'
    | '/guides/sell/$food/$state'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/compare'
    | '/sitemap.xml'
    | '/foods/$slug'
    | '/states/$slug'
    | '/foods'
    | '/guides'
    | '/states'
    | '/guides/labeling/$state'
    | '/guides/license-cost/$state'
    | '/guides/sell/$food/$state'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/compare'
    | '/sitemap.xml'
    | '/foods/$slug'
    | '/states/$slug'
    | '/foods/'
    | '/guides/'
    | '/states/'
    | '/guides/labeling/$state'
    | '/guides/license-cost/$state'
    | '/guides/sell/$food/$state'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CompareRoute: typeof CompareRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  FoodsSlugRoute: typeof FoodsSlugRoute
  StatesSlugRoute: typeof StatesSlugRoute
  FoodsIndexRoute: typeof FoodsIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  StatesIndexRoute: typeof StatesIndexRoute
  GuidesLabelingStateRoute: typeof GuidesLabelingStateRoute
  GuidesLicenseCostStateRoute: typeof GuidesLicenseCostStateRoute
  GuidesSellFoodStateRoute: typeof GuidesSellFoodStateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states/': {
      id: '/states/'
      path: '/states'
      fullPath: '/states/'
      preLoaderRoute: typeof StatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods/': {
      id: '/foods/'
      path: '/foods'
      fullPath: '/foods/'
      preLoaderRoute: typeof FoodsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states/$slug': {
      id: '/states/$slug'
      path: '/states/$slug'
      fullPath: '/states/$slug'
      preLoaderRoute: typeof StatesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods/$slug': {
      id: '/foods/$slug'
      path: '/foods/$slug'
      fullPath: '/foods/$slug'
      preLoaderRoute: typeof FoodsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/license-cost/$state': {
      id: '/guides/license-cost/$state'
      path: '/guides/license-cost/$state'
      fullPath: '/guides/license-cost/$state'
      preLoaderRoute: typeof GuidesLicenseCostStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/labeling/$state': {
      id: '/guides/labeling/$state'
      path: '/guides/labeling/$state'
      fullPath: '/guides/labeling/$state'
      preLoaderRoute: typeof GuidesLabelingStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/sell/$food/$state': {
      id: '/guides/sell/$food/$state'
      path: '/guides/sell/$food/$state'
      fullPath: '/guides/sell/$food/$state'
      preLoaderRoute: typeof GuidesSellFoodStateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CompareRoute: CompareRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  FoodsSlugRoute: FoodsSlugRoute,
  StatesSlugRoute: StatesSlugRoute,
  FoodsIndexRoute: FoodsIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  StatesIndexRoute: StatesIndexRoute,
  GuidesLabelingStateRoute: GuidesLabelingStateRoute,
  GuidesLicenseCostStateRoute: GuidesLicenseCostStateRoute,
  GuidesSellFoodStateRoute: GuidesSellFoodStateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
